apiVersion: v1
kind: Service
metadata:
  name: nginx-rtmp-service
spec:
  type: NodePort
  selector:
    app: nginx-rtmp
  ports:
  - name: rtmp
    port: 1935
    targetPort: 1935
    nodePort: 31031


