apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-rtmp-deployment
spec:
  replicas: 2  		# pods para tolerancia a fallos
  selector:
    matchLabels:
      app: nginx-rtmp
  template:
    metadata:
      labels:
        app: nginx-rtmp
    spec:
      containers:
      - name: nginx-rtmp
        image: tiangolo/nginx-rtmp
        ports:
        - containerPort: 1935
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-rtmp-service  	#utiliza el mismo nombre que el servicio anterior (se actualizará)
spec:
  type: NodePort
  selector:
    app: nginx-rtmp
  ports:
  - name: rtmp
    port: 1935
    targetPort: 1935
    nodePort: 31032		#cambio de puerto en el servicio (se actualizará)


