apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-rtmp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-rtmp
      role: streaming
  template:
    metadata:
      labels:
        app: nginx-rtmp
        role: streaming      #etiqueta de los pod que seran buscados por el servicio
    spec:
      containers:
      - name: streaming
        image: tiangolo/nginx-rtmp
        ports:
        - containerPort: 1935

---
apiVersion: v1
kind: Service
metadata:
  name: streaming-service
spec:
  type: LoadBalancer  
  ports:
  - port: 1935
    targetPort: 1935
    nodePort: 31031
  selector:
    role: streaming       #los pod que seran los back end para el servicio


